name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Add User
        run: sudo useradd -p $(openssl passwd -1 remoteuser) remoteuser

      - name: Add User to Sudo
        run: sudo usermod -aG sudo remoteuser

     




      # - name: Install xubuntu
        # run: sudo apt install xubuntu-desktop -y

      - name: Install Gnome
        run: sudo apt install ubuntu-desktop -y


      # - name: Install XRDP
      #   run: sudo apt install xrdp -y
        
      # - name: Add XRDP user
      #   run: sudo adduser xrdp ssl-cert  

                
      # - name: restart XRDP
      #   run: sudo systemctl restart xrdp 

      # - name: Firewall enable
      #   run: sudo ufw enable

      # - name: Firewall Show
      #   run: sudo ufw status


      # - name: Firewall enable
      #   run: sudo ufw allow 3389/tcp

      # - name: restart XRDP
      #   run: sudo systemctl restart xrdp 

      - name: install ngrock
        run: sudo snap install ngrok
      - name: set key
        run: ngrok authtoken 1pvCLPonkOTvl3KElXPS9U9Iua1_2iMqrC7PRvJJWerNx7K5h

      - name: check ngrock
        run: ngrok tcp 3389 & 
        
      - name: Get Info
        run: curl -s http://localhost:4040/api/tunnels

      - name: Get IP
        run: dig +short myip.opendns.com @resolver1.opendns.com
      - name: Ping
        run: ping 127.0.0.1

      



