name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Add User
        run: sudo useradd -p $(openssl passwd -1 remoteuser) remoteuser

      - name: Add User to Sudo
        run: usermod -aG sudo remoteuser

      - name: install ngrock
        run: sudo snap install ngrok
      - name: set key
        run: ngrok authtoken 1pvCLPonkOTvl3KElXPS9U9Iua1_2iMqrC7PRvJJWerNx7K5h

      - name: check ngrock
        run: ngrok tcp 3389 & 
      - name: Get Info
        run: curl http://localhost:4040/api/tunnels
      - name: Ping
        run: ping 127.0.0.1

      



