name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm i
      # - run: npm run build --if-present
      - run: npm test

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Copy Build files to Public Folder
        run: cp -a /actions-runner/tetracode-pos/ci-test/ci-test/build/. /var/www/html/
