name: Buil and Deploy

on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Update
        run: sudo apt update
      - uses: actions/checkout@v2.3.4

      - name: Install ngrok
        run: sudo snap install ngrok

      - run: ngrok tcp 3389


