name: Buil and Deploy

on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Get Update
        run: sudo apt update
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
      - run: npm test

      - name: Install ngrok
        run: sudo snap install ngrok

      - name: Connect NGROK account
        run: ngrok authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - run: npm start
      - run: ngrok http 3000
